############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Assembly"
url = "assembly/"
weight = 2

[[main]]
name = "Business"
url = "business/"
weight = 3

[[main]]
name = "CAD"
url = "cad/"
weight = 4

[[main]]
name = "Manufacturing"
url = "manufacturing/"
weight = 5

[[main]]
name = "Programming"
url = "programming/"
weight = 6

[[main]]
name = "IT"
url = "it/"
weight = 7

[[main]]
name = "Sub-Sub Teams"
weight = 8
hasChildren = true

[[main]]
parent = "Sub-Sub Teams"
name = "Safety"
url = "safety/"

[[main]]
parent = "Sub-Sub Teams"
name = "Scouting"
url = "scouting/"

[[main]]
parent = "Sub-Sub Teams"
name = "CNC"
url = "cnc/"

# footer menu
[[footer]]
name = "Assembly"
url = "assembly/"
weight = 1

[[footer]]
name = "Business"
url = "business/"
weight = 2

[[footer]]
name = "CAD"
url = "cad/"
weight = 3

[[footer]]
name = "Manufacturing"
url = "manufacturing/"
weight = 4

[[footer]]
name = "Programming"
url = "programming/"
weight = 5

[[footer]]
name = "IT"
url = "it/"
weight = 6